// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	entity "recycle/features/detail_pickup/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// DetailPickupDataInterface is an autogenerated mock type for the DetailPickupDataInterface type
type DetailPickupDataInterface struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields:
func (_m *DetailPickupDataInterface) BeginTransaction() (*gorm.DB, error) {
	ret := _m.Called()

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func() (*gorm.DB, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: data
func (_m *DetailPickupDataInterface) Create(data []entity.Main) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]entity.Main) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllDetailPickup provides a mock function with given fields:
func (_m *DetailPickupDataInterface) FindAllDetailPickup() ([]entity.Main, error) {
	ret := _m.Called()

	var r0 []entity.Main
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Main, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Main); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Main)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDetailPickupDataInterface creates a new instance of DetailPickupDataInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDetailPickupDataInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DetailPickupDataInterface {
	mock := &DetailPickupDataInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
